#!/usr/bin/env python
import sys

import systemd.journal
from plumbum.cmd import ip

NETWORKMANAGER_OPENVPN_IDENTIFIER = 'nm-openvpn'
LINK_REMOTE_PREFIX = 'UDPv4 link remote: [AF_INET]'


def get_default_gateway():
    for line in ip('route').splitlines():
        # Return first default gateway found that isn't a virtual tunnel device
        if line.startswith('default via') and 'dev tun' not in line:
            return line.split('default via')[1].split(None, 1)[0]


def main():
    reader = systemd.journal.Reader()
    reader.this_boot()
    reader.add_match(SYSLOG_IDENTIFIER=NETWORKMANAGER_OPENVPN_IDENTIFIER)

    prefix_length = len(LINK_REMOTE_PREFIX)
    while True:
        for entry in reader:
            message = entry['MESSAGE']
            if not message.startswith(LINK_REMOTE_PREFIX):
                continue

            gateway = get_default_gateway()
            if not gateway:
                print('Error: Could not determine default gateway:', file=sys.stderr)
                print(ip('route'), file=sys.stderr)
                continue

            address = message[prefix_length:].split(':', 1)[0]
            ip('route', 'add', address, 'via', gateway, retcode=None)
            print('Added', address, 'to whitelist')
        reader.wait()


if __name__ == '__main__':
    main()
