#!/usr/bin/env python

import argparse
import os
import subprocess

argument_parser = argparse.ArgumentParser(description='List files installed by a package contained in PATH.')
argument_parser.add_argument('package')

EXIT_FAILURE = 1


def get_command_stdout(*arguments):
    try:
        return subprocess.check_output(arguments, universal_newlines=True, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        pass


def get_owned_files(name):
    output = get_command_stdout('pacman', '-Qlq', name)
    if not output:
        argument_parser.exit(EXIT_FAILURE, 'Could not find package.\n')

    return [p for p in output.split() if os.path.isfile(p)]


def main(arguments):
    PATH = os.getenv('PATH').split(os.pathsep)
    for path in get_owned_files(arguments.package):
        if any(path.startswith(p) for p in PATH):
            print(path)


if __name__ == '__main__':
    arguments = argument_parser.parse_args()
    main(arguments)
