#!/usr/bin/env python

import time

from plumbum import NOHUP
from plumbum.cmd import killall, plasmashell

RESTART_DELAY = 1


def main():
    killall('plasmashell', retcode=None)

    # Add a small delay: if plasmashell is restarted too quickly it will fail to start
    time.sleep(RESTART_DELAY)
    plasmashell & NOHUP(stdout='/dev/null')


if __name__ == '__main__':
    main()
