#!/usr/bin/env python

from plumbum import local
from plumbum.cmd import wall


def main():
    message = 'S.M.A.R.T. Failure (%s)\n\n%s' % (local.env['SMARTD_FAILTYPE'], local.env['SMARTD_FULLMESSAGE'])
    wall(message)


if __name__ == '__main__':
    main()
