#!/usr/bin/env python

import argparse
import collections
import itertools
import json
import os
import sys
import textwrap

from plumbum.cmd import systemctl

argument_parser = argparse.ArgumentParser()
argument_parser.add_argument('--destination', '-d', default='list-unit-files.json',
                             help='Change destination of output file')
argument_parser.add_argument('--compare', '-c', nargs=2, help='Compare first output to second output')


def compare(a_path, b_path):
    with open(a_path) as file:
        a = json.load(file)
    with open(b_path) as file:
        b = json.load(file)

    a_file_name = os.path.basename(a_path)
    b_file_name = os.path.basename(b_path)
    states = set(s for s in itertools.chain(a.keys(), b.keys()))
    for state in states:
        a_set = set(a.get(state, []))
        b_set = set(b.get(state, []))

        print('Missing %s in %s:' % (state, b_file_name))
        result = '\n'.join(sorted(a_set.difference(b_set)))
        result = result or 'None'
        print(textwrap.indent(result, '    - '))
        print()
        print('Missing %s in %s:' % (state, a_file_name))
        result = '\n'.join(sorted(b_set.difference(a_set)))
        result = result or 'None'
        print(textwrap.indent(result, '    - '))
        print()


def main(arguments):
    if arguments.compare:
        return compare(*arguments.compare)

    data = collections.defaultdict(list)
    output = systemctl('list-unit-files', '--no-pager')
    for line in output.splitlines()[1:-2]:
        unit, state = line.split(None, 1)
        data[state.strip()].append(unit.strip())

    with open(arguments.destination, 'w') as file:
        json.dump(data, file)


if __name__ == '__main__':
    sys.exit(main(argument_parser.parse_args(sys.argv[1:])))
